### ISSUE TITLE
A couple of missing steps inside the C procedure

### ISSUE THREAD

**Issue by dcabanis** [gurgleapps/pico-pi#1]
Once you have downloaded the SDK from GitHub you will need to initialise the TinyUSB submodule by doing: ```sh git submodule update --init```

You will also have to create a `build` directory before `cd` into it.

Lastly, the `PICO_SDK_PATH` environment variable is specific to your installation it might be worth mentioning that is needs tuning

**Comment by mirkin** [comment]
Great points, thanks.
